name:                haskellcas
version:             0.1.0.0
github:              "githubuser/haskellcas"
license:             BSD3
author:              "Steven Canning"
maintainer:          "spcanning@gmail.com"
copyright:           "2019 Steven Canning"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskellcas#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskellcas-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellcas

tests:
  haskellcas-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellcas
